『Testing』翻译完成
ourmeteor/guide-zh pull request #27
Opened 2016-10-25 18:25 UTC by FrostyLeaf

TODO:

- [x] 根据 [README.md](https://github.com/ourmeteor/guide-zh/blob/master/README.md) 检查行文格式，尤其注意：
  - [x] 中西文间空格，标点与西文无需空格。
  - [x] 使用方引号（「『』」）而不是弯引号。
  - [x] 一致使用全角标点，而不是混用，保留的英文原句内除外。
- [x] 翻译所有代码内的注释。
- [x] 空行形式与原文统一。
- [x] 根据[术语表](https://github.com/ourmeteor/guide-zh/wiki/%E6%9C%AF%E8%AF%AD%E8%A1%A8)检查专有名词用词规范性。

2016-10-25 22:24 UTC, laosb requested changes
Review 至 80 行

2016-10-25 22:24 UTC, laosb commented on content/testing.md
> +description: 如何测试你的 meteor 应用
Meteor 专有名词首字母大写，只在提及命令行上的 meteor 时用小写。

2016-10-25 22:24 UTC, laosb commented on content/testing.md
> +- **单元测试**：如果你正在（编写代码）测试你应用中的一个小模块，那么这意味着你编写的是单元测试。你需要 *"stub"* 并 *"mock"* 经常被该模块所影响的其他模块，以便于 *隔离* 各个测试。你通常还需要 *监视* 该模块的动作以验证它们已经发生。
这几个名词我觉得可以提供一下英文原文

2016-10-25 22:24 UTC, laosb commented on content/testing.md
> +- **实时响应**：Meteor 的实时响应系统是『最终一致性』的，这意味着当你更改了一个具有响应性的输入至系统中后，在一段时间后，你将会看到用户界面发生相应的更改。这会是测试工作中的一个挑战，但也有一些方式可以等到这些更改发生之后再验证测试结果，例如 `Tracker.afterFlush()` 。
单方引号为外层，双方引号为内层，多级嵌套时交替使用

2016-10-25 22:24 UTC, laosb commented on content/testing.md
> +这一命令会使用一个特殊的『测试模式』来加载你的应用，它会做以下几件事：
同上

2016-10-25 22:24 UTC, laosb commented on content/testing.md
> +这意味着，您的应用程序整体（例如包括 Web 服务器和客户端的路由器）会像在普通模式下一样正常加载和运行。这使你能够编写更复杂的[集成测试](#full-app-integration-test)，同时装入其他文件进行[验收测试](#acceptance-testing)。
装入 改为 载入 更符合习惯些

2016-10-25 22:24 UTC, laosb commented on content/testing.md
> +注意，在 Meteor 工具中还有一条测试命令：`meteor test-packages`，用于测试 Atmosphere 包，我们将在[如何编写 packages](writing-packages.html#testing) 中进行讨论。
编写包

2016-10-25 22:24 UTC, laosb commented on content/testing.md
多了个空行

2016-10-25 22:24 UTC, laosb commented
@FrostyLeaf 感谢：）请作对应修改

2016-10-26 04:13 UTC, FrostyLeaf commented
感谢@laosb的辛勤校对，我会尽快修改！

2016-10-28 19:12 UTC, FrostyLeaf commented
@laosb 已经更改并且提交，请再次 review，谢谢！

2016-10-28 22:24 UTC, laosb requested changes
To 448

2016-10-28 22:24 UTC, laosb commented on content/testing.md
>  不过，在 Meteor 应用中（如果被测试的模块正好跨越了客户端 - 服务端边界），跨越了客户端 - 服务端边界的集成测试，需要一个独特的底层技术的支持，即 Meteor 的 "full app" 测试模式。
使用破折号——

2016-10-28 22:24 UTC, laosb commented on content/testing.md
>  不过，在 Meteor 应用中（如果被测试的模块正好跨越了客户端 - 服务端边界），跨越了客户端 - 服务端边界的集成测试，需要一个独特的底层技术的支持，即 Meteor 的 "full app" 测试模式。
另外 full app 直接译为全应用或者完整应用就好了

2016-10-28 22:24 UTC, laosb approved these changes

2016-10-29 06:21 UTC, FrostyLeaf commented on content/testing.md
>  不过，在 Meteor 应用中（如果被测试的模块正好跨越了客户端 - 服务端边界），跨越了客户端 - 服务端边界的集成测试，需要一个独特的底层技术的支持，即 Meteor 的 "full app" 测试模式。
混排的问题上次用正则查了一遍，但是貌似还是没改完。
破折号不清楚你说的是哪个地方呢？我没发现还有没替换的破折号啊。如果是“客户端 - 服务端”这个的话，是不能用破折号的。

2016-10-29 06:34 UTC, laosb commented on content/testing.md
>  不过，在 Meteor 应用中（如果被测试的模块正好跨越了客户端 - 服务端边界），跨越了客户端 - 服务端边界的集成测试，需要一个独特的底层技术的支持，即 Meteor 的 "full app" 测试模式。
根据[「连接号」的维基百科页面（链接导引至 Wikiwand 等效页面）](https://www.wikiwand.com/zh/%E8%BF%9E%E6%8E%A5%E5%8F%B7)，应该是连接号而不是破折号，即半个破折号。

2016-10-29 07:19 UTC, FrostyLeaf reviewed
1. 已经补充了中英混排时缺失的空格（半角）。
2. 遗漏的 "full app" 已经修改为「全应用」，与其他各处的翻译统一。

2016-10-29 07:20 UTC, laosb commented
LGTM. Merging. Thank you for your contribution!

2016-10-29 07:20 UTC, merged